/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DeividRouteImport } from './routes/deivid'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DeividRoute = DeividRouteImport.update({
  id: '/deivid',
  path: '/deivid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/deivid': typeof DeividRoute
  '/home': typeof HomeRoute
}
export interface FileRoutesByTo {
  '/deivid': typeof DeividRoute
  '/home': typeof HomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/deivid': typeof DeividRoute
  '/home': typeof HomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/deivid' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/deivid' | '/home'
  id: '__root__' | '/deivid' | '/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeividRoute: typeof DeividRoute
  HomeRoute: typeof HomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deivid': {
      id: '/deivid'
      path: '/deivid'
      fullPath: '/deivid'
      preLoaderRoute: typeof DeividRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DeividRoute: DeividRoute,
  HomeRoute: HomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
